# roslaunch tr_drive car_wbt_repeat.launch path:="/home/gralerfics/MyFiles/Workspace/tr_data/car_1"
tr:
    camera:
        raw_image_topic: /car/camera/image
        processed_image_topic: /tr/camera/processed_image # debug
    odometry:
        odom_topic: /car/odom
        processed_odom_topic: /tr/odometry/processed_odom # debug
    controller:
        cmd_vel_topic: /car/cmd_vel
        k_rho: 0.45 # 0.5 # k_rho > 0
        k_alpha: 2.0 # 5.0 # k_alpha > k_rho
        k_beta: -0.5 # -3.0 # k beta < 0
        k_theta: 4.0 # 7.0
        velocity_min: 0.0
        velocity_max: 0.2
        omega_min: 0.15
        omega_max: 0.93 # TODO
        translation_tolerance: 0.05
        rotation_tolerance: 0.1
    global_locator:
        type: 'webots'
        fixed_frame_id: 'map'
        supervisor_srv: '/car/supervisor'
        robot_def: 'car'
    repeater:
        match_offset_radius: 90 # px
        along_path_radius: 2
        k_rotation: 0.04 # 0.06 # 0.01; [!] may be related to time step
        k_along_path: 0.03 # 0.04 # 0.03
        distance_threshold: 0.01
        angle_threshold: 0.05
        goal_advance_distance: 0.2