# roslaunch tr_drive tb3_teach.launch folder:="/home/gralerfics/MyFiles/Workspace/tr_data"
tr:
    camera:
        raw_image_topic: /tb3/camera/image
        patch_size: 15
        resize: [150, 50] # [width, height]
        horizontal_fov: 114.59 # degree
        processed_image_topic: /tr/camera/processed_image # debug
    odometry:
        odom_topic: /tb3/controller/odom
        processed_odom_topic: /tr/odometry/processed_odom # debug
        # ground_truth_odom_topic: /amcl_pose
    teacher:
        save_raw_images: true
        save_ground_truth_odoms: true
        rotation_threshold: 0.08 # rad
        translation_threshold: 0.04 # m