# roslaunch tr_drive tb3_repeat.launch path:="/home/gralerfics/MyFiles/Workspace/tr_data/2024-02-12_17:55:53"
tr:
    camera:
        raw_image_topic: /tb3/camera/image
        processed_image_topic: /tr/camera/processed_image # debug
    odometry:
        odom_topic: /tb3/controller/odom
        processed_odom_topic: /tr/odometry/processed_odom # debug
    controller:
        cmd_vel_topic: /tb3/controller/cmd_vel
        k_rho: 0.35 # 0.5 # k_rho > 0
        k_alpha: 3.5 # 5.0 # k_alpha > k_rho
        k_beta: -2.0 # -3.0 # k beta < 0
        k_theta: 7.0
        velocity_min: 0.0
        velocity_max: 0.2
        omega_min: 0.15
        omega_max: 0.93 # TODO
        translation_tolerance: 0.05
        rotation_tolerance: 0.1
    global_locator:
        type: 'tf'
        fixed_frame: '/map'
        # topic: '/amcl_pose'
        # topic_type: 'PoseWithCovarianceStamped'
    repeater:
        match_offset_radius: 90 # px
        along_path_radius: 2
        k_rotation: 0.01
        k_along_path: 0.02
        distance_threshold: 0.01
        angle_threshold: 0.02
        goal_advance_distance: 0.15