# roslaunch tr_drive tb3_repeat.launch path:="/home/gralerfics/MyFiles/Workspace/tr_data/2024-02-12_17:55:53"
tr:
    camera:
        raw_image_topic: /tb3/camera/image
        processed_image_topic: /tr/camera/processed_image # debug
    odometry:
        odom_topic: /tb3/controller/odom
        processed_odom_topic: /tr/odometry/processed_odom # debug
    controller:
        cmd_vel_topic: /tb3/controller/cmd_vel